// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const button: string;
export const buttonGreen: string;
export const buttonSideRight: string;
export const buttonMobileFullSize: string;
