// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const content: string;
export const content__container: string;
export const content__containerOpened: string;
export const content__controller: string;
export const content__controllerHandled: string;
export const content__wrap: string;
export const content__map: string;
export const content__title: string;
export const content__sideBar: string;
export const content__sideBarCentered: string;
export const content__point: string;
