// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const forecast: string;
export const forecast__wrapper: string;
export const forecast__title: string;
export const forecast__container: string;
export const forecast__item: string;
export const forecast__itemHeading: string;
export const forecast__itemWeatherGroup: string;
export const forecast__itemTemperature: string;
export const forecast__itemDescription: string;
export const forecast__itemStats: string;
export const forecast__itemStatsRow: string;
