// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const header__container: string;
export const header__icon: string;
export const header__field: string;
export const header__results: string;
export const header__resultsItem: string;
export const header__resultsItemActive: string;
export const header__title: string;
export const header__close: string;
export const header__location: string;
