export * as ButtonStyles from "./Button.module.scss"
export * as ContentStyles from "./Content.module.scss"
export * as IconStyles from "./Icon.module.scss"
export * as LoaderStyles from "./Loader.module.scss"
export * as WeatherStyles from "./Weather.module.scss"
export * as HeaderStyles from "./Header.module.scss"
export * as ForecastStyles from "./Forecast.module.scss"
export * as PromptStyles from "./Prompt.module.scss"
