// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const prompts__list: string;
export const prompts__item: string;
export const prompts__content: string;
export const prompts__title: string;
export const prompts__icon: string;
export const prompts__iconSuccess: string;
export const prompts__iconError: string;
export const prompts__close: string;
