// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const weather__header: string;
export const weather__row: string;
export const weather__temperature: string;
export const weather__description: string;
export const weather__stats: string;
export const weather__statsRow: string;
export const weather__statsLabelWithIcon: string;
export const weather__statsData: string;
export const weather__dataContainer: string;
export const weather__chart: string;
